# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HFHj5GKA1Maudw3jQDsg25BN3rx_Y_Ep
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import gc
import numpy as np

import pickle
file_name = "input/xgb_clf.pkl"

# loading the model
xgb_model_loaded = pickle.load(open(file_name, "rb"))

cols=pd.read_csv("input/header.csv")
dfpred = pd.read_csv("input/Storage_Systems_SMART.csv", usecols=cols)

cols_raw_pred=filter(lambda x: 'raw' in x, list(dfpred.columns))
cols_nomrmalized_pred=filter(lambda x: 'normalized' in x, list(dfpred.columns))

df_raw_pred = dfpred[cols_raw_pred]
df_norm_pred = dfpred[cols_nomrmalized_pred].sample(22)
X_pred = df_norm_pred.values

# test
res=xgb_model_loaded.predict(X_pred)
print (res)

liste=list(res)
listshow=[]
for i in liste:
  if i==1 :
    index=liste.index(i)
    listshow.append(index)

dfshow=dfpred.iloc[listshow]
dfshow.to_csv(r'output/dftoshow.csv', sep='\t', encoding='utf-8', header='true')